version: '3'

services:

  core:
    container_name: core.budgetcontrol.lan
    image: mlabfactory/php8-fmp:v1.0
    volumes:
      - ./:/var/www/workdir
      - ../logapp:/app/storage/logs
      - ./bin/apache/default.conf:/etc/apache2/sites-available/budgetcontrol.cloud.conf
    depends_on:
      - database
      - cache
    networks:
      - budgetcontrol_network
    restart: unless-stopped

  proxy:
    platform: linux/x86_64
    container_name: proxy.budgetcontrol.lan
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./bin/nginx/:/etc/nginx/conf.d/
      - ./bin/certbot/conf:/etc/letsencrypt
      - ./bin/certbot/www:/var/www/certbot
    networks:
      - budgetcontrol_network
    depends_on:
      - core

  certbot:
    image: certbot/certbot
    container_name: budgetcontrol-certbot
    volumes:
    - ./bin/certbot/conf:/etc/letsencrypt
    - ./bin/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - budgetcontrol_network
      
  ms-stats:
    container_name: stats.ms.budgetcontrol.lan
    image: mlabfactory/php8-fmp:v1.0
    volumes:
      - ./microservices/Stats/:/var/www/workdir
      - ./bin/apache/default.conf:/etc/apache2/sites-available/budgetcontrol.cloud.conf
    networks:
      - budgetcontrol_network
    restart: unless-stopped
    depends_on:
      - database
  
  ms-workspace:
    container_name: workspace.ms.budgetcontrol.lan
    image: mlabfactory/php8-fmp:v1.0
    volumes:
      - ./microservices/Workspace/:/var/www/workdir
      - ./bin/apache/default.conf:/etc/apache2/sites-available/budgetcontrol.cloud.conf
    networks:
      - budgetcontrol_network
    restart: unless-stopped
    depends_on:
      - database
  
  gateway:
    container_name: gateway.budgetcontrol.lan
    image: mlabfactory/php8-fmp:v1.0
    volumes:
      - ./microservices/Gateway/:/var/www/workdir
      - ./bin/apache/default.conf:/etc/apache2/sites-available/budgetcontrol.cloud.conf
    networks:
      - budgetcontrol_network
    restart: unless-stopped
    depends_on:
      - database

  ms-authentication:
    container_name: authentication.ms.budgetcontrol.lan
    image: mlabfactory/php8-fmp:v1.0
    volumes:
      - ./microservices/Authentication/:/var/www/workdir
      - ./bin/apache/default.conf:/etc/apache2/sites-available/budgetcontrol.cloud.conf
    networks:
      - budgetcontrol_network
    restart: unless-stopped
    depends_on:
      - database

  ms-jobs:
    container_name: jobs.ms.budgetcontrol.lan
    image: mlabfactory/php8-fmp:v1.0
    volumes:
      - ./microservices/CommandJobs/:/var/www/workdir
      - ./bin/apache/default.conf:/etc/apache2/sites-available/budgetcontrol.cloud.conf
    networks:
      - budgetcontrol_network
    restart: unless-stopped
    depends_on:
      - database

  ms-budget:
    container_name: budget.ms.budgetcontrol.lan
    image: mlabfactory/php8-fmp:v1.0
    volumes:
      - ./microservices/Budget/:/var/www/workdir
      - ./bin/apache/default.conf:/etc/apache2/sites-available/budgetcontrol.cloud.conf
    networks:
      - budgetcontrol_network
    restart: unless-stopped
    depends_on:
      - database

  ms-entries:
    container_name: entries.ms.budgetcontrol.lan
    image: mlabfactory/php8-fmp:v1.0
    volumes:
      - ./microservices/Entries/:/var/www/workdir
      - ./bin/apache/default.conf:/etc/apache2/sites-available/budgetcontrol.cloud.conf
    networks:
      - budgetcontrol_network
    restart: unless-stopped
    depends_on:
      - database

  ms-wallets:
    container_name: wallets.ms.budgetcontrol.lan
    image: mlabfactory/php8-fmp:v1.0
    volumes:
      - ./microservices/Wallets/:/var/www/workdir
      - ./bin/apache/default.conf:/etc/apache2/sites-available/budgetcontrol.cloud.conf
    networks:
      - budgetcontrol_network
    restart: unless-stopped
    depends_on:
      - database

  ms-searchengine:
    container_name: searchengine.ms.budgetcontrol.lan
    image: mlabfactory/php8-fmp:v1.0
    volumes:
      - ./microservices/SearchEngine/:/var/www/workdir
      - ./bin/apache/default.conf:/etc/apache2/sites-available/budgetcontrol.cloud.conf
    networks:
      - budgetcontrol_network
    restart: unless-stopped
    depends_on:
      - database

networks:
  budgetcontrol_network:
    external: true
    name: budgetcontrol_network
