version: '2.2'

services:
    database:
      image: mysql:latest
      restart: unless-stopped
      env_file:
        - .env
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
    bemodule:
      image: docker.io/bitnami/laravel:10
      env_file:
        - .env
      ports:
        - 3333:8000
      volumes:
        - ./:/app
        - .env:/app/.env
      depends_on:
        - database
      restart: unless-stopped
      command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"