version: '2.2'

services:
    proxy:
      volumes:
        - ./bin/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./bin/certbot/conf:/etc/letsencrypt
        - ./bin/certbot/www:/var/www/certbot

    ms-stats:
      image: mlabfactory/php8-apache:v1.0-xdebug
      ports:
        - "8084:80"
    
    ms-workspace:
      image: mlabfactory/php8-apache:v1.0-xdebug
      ports:
        - "8082:80"
    
    gateway:
      image: mlabfactory/php8-apache:v1.0-xdebug
      ports:
        - "8081:80"

    ms-authtentication:
      image: mlabfactory/php8-apache:v1.0-xdebug
      ports:
        - "8083:80"

    ms-budget:
      image: mlabfactory/php8-apache:v1.0-xdebug
      ports:
        - "8085:80"

    database:
      ports:
        - "3336:3306"

    core:
      image: mlabfactory/php8-apache:v1.0-xdebug
      ports:
        - "3000:80"

volumes:
  mysql_persistent:
    name: budgetcontrol_core_database
    external: false
  cache:
    name: budgetcontrol_core_cache
    external: false
