version: '2.2'

services:
    database:
      ports:
        - 3366:3306
    mailhog:
      container_name: budgetcontrol-mailhog
      image: mailhog/mailhog:latest
      restart: always
      ports:
        - 1025:1025
        - 8025:8025
      networks:
        - budgetcontrol_network
    bemodule:
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - 3000:80
