version: '3'

services:

  database:
    platform: linux/x86_64
    container_name: budgetcontrol-db
    image: mysql:8.0.36-debian
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_persistent:/var/lib/mysql
    networks:
      - budgetcontrol_network

  cache:
    platform: linux/x86_64
    container_name: budgetcontrol-redis
    image: redis:7.2-rc2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - budgetcontrol_network

volumes:
  mysql_persistent:
    name: budgetcontrol_core_database
    external: true
  cache:
    name: budgetcontrol_core_cache
    external: true

networks:
  budgetcontrol_network:
    external: true
    name: budgetcontrol_network
